sudo: false
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '0.12'
before_install: npm install -g grunt-cli
after_success: grunt travis
deploy:
  provider: npm
  email: ag-hostmaster+npm@appgyver.com
  on:
    tags: true
    all_branches: true
    repo: AppGyver/ag-magic-model
  api_key:
    secure: IvGB6rwY0GxbxmrI781+A2Ty1ASifHN8c1XvCMmMg4prHimIkB6BZS+vLUa1iYMyv5lm7RbnwPWEdnjFC9zt28IGurFh4TzOhX3edEbI8ANDeBorILkjN9G9gAGDP63qDFvG0d3ndo9/rbJKdEA/UZBRE88vYDgsqLOqcVqhMUdEensAn52l55Rnbewgrl15gYWsKxL0HcDV99wBgLoAMzqtpH5DsidHy4wAc9INSfHy7UynQe/AkRMJlan3o3swQ2s/BvEJGeXmfb1gptfaNbEGpXZ+m1Uj8KeG6cma0zfzsvSjwMk2EnHYcjYaPq7h1KC9F5riij7ntTJRLnGw6IlebYFEd49wX3usECNqWamrerRhrokIXj/ZKsJPG21VIbqZGUHDoE1zdq7/p0kH3zON80qdwf1S0VN+HS1FBBH3RsfUmLR8PBUm9i6gUQj7zpBlzxslgZhU3pQtlY/aNpuvM9B5QcfIvfn6qErxQW9XGmFaJflyAZl3N6AV7nMsbDEED5zSgcL50RUt5IhCLfomzU5VsN7dN4CE7s39sEscgfNnFl+yKwm2lJes8tp3jgcR+5dGoebIMlHDyZb/mR4BMkQp4NjMmTeaZu8/+FxGgg2Ytoq1qrwVbf1GiwS4TydFTPf2vGiZqNokDzONQKxHkIfZ6EPyjmfea3B04vo=
env:
  global:
    secure: fd15uBi2CnDnhoyWWY1/oe1tDtwNX4fZ4OKiBC7RCKqiYLB648SkluVrOEdueg7Ckl/mhGAiSa/OcB/wuWOK66G1UIHLYIg/JJaruDd7Fad6vV4ihjJK/VbimBJwRkKgOaAI0z+xeEy7dnw5yaHtJh3aZIqjQlJXIu476D+2fP+E3pfuukT552tbPN7Y0TEqoL0z3NvojLlGPe+9i1X//u4OLUN43OcvSFyB3xipilVxm2ovLQW46EWrcXv6+drso4/u3RgSsj0MaI2PkNpbHdO+YmGTbyeuK31TeCEmAbcwaQbSh0TJmYG9Gmh9x9TPX8xP399EMqkJgHa+szGEbFnm5eWyjYudvX/DX9zlcPOfN1N+pxoVFE9Xx9CILWrhPr4bgKQdbibZ33yhSEprQDLztPWW8plL8FVIv5RpXJr4b/zxq/cxv04xMtTgk3ur9u50m3WEGuP+4zOEj3Z7k3siMRoXEuLiNRCt6yi2ti+25r3nn0JqPU1rGy1wC93qy6HmIbXXFReWTF6vVBaJqV98NqcJw+avaocNhLnv3o5xiWSvk+SeeSuqxwnHQBJZjwzXkQXaC653dtOYiOcnQI2GiQGzbtgN1MJ4K+d4RWqz8O2lxgUKg9NoTsJ7WIrSwYpw2wAIxADhjw8ZRYVTWcv/PyqDbRSxOC8u86/IJAg=
